#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use Alquesadilla\Enforcer\EnforcerCheckCommand;
use Illuminate\Filesystem\Filesystem;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Illuminate\Container\Container;

$enforcerConfigs = ['enforcer' => require_once(__DIR__ . '/config/enforcer.php'), 'app' => ['env' => 'local']];
$config = new Illuminate\Config\Repository($enforcerConfigs);

$enforcer = new EnforcerCheckCommand($config, new Filesystem());
$enforcer->setLaravel(new Container());

$params = [];

if (isset($argv[1])) {
    $params['branch'] = $argv[1];
    $params['--outputOnly'] = true;
}

$enforcer->run(
    new ArrayInput(
        $params,
        new InputDefinition([
            new InputArgument('enforcer', InputArgument::OPTIONAL, null, 'check'),
            new InputOption('githook'),
            new InputOption('outputOnly'),
            new InputArgument('branch', InputArgument::OPTIONAL)
        ])
    ),
    new ConsoleOutput(ConsoleOutput::VERBOSITY_DEBUG)
);
